### ISSUE TITLE
No module named 'translation_agent' help wanted

### ISSUE THREAD

**Issue by Prthm17** [andrewyng/translation-agent#46]
I am really very new to programming, forgive me if this is a stupid question but,
When I try to run app.py I receive below error:

Traceback (most recent call last):
  File "/content/translation-agent/app/app.py", line 6, in <module>
    from process import (
  File "/content/translation-agent/app/process.py", line 8, in <module>
    from patch import (
  File "/content/translation-agent/app/patch.py", line 9, in <module>
    import translation_agent.utils as utils
ModuleNotFoundError: No module named 'translation_agent'

**Comment by wq163** [comment]
python app/app.py
Traceback (most recent call last):
  File "/translation-agent-main/app/app.py", line 6, in <module>
    from process import (
  File "/translation-agent-main/app/process.py", line 8, in <module>
    from patch import (
  File "/translation-agent-main/app/patch.py", line 37
    match endpoint:
          ^
SyntaxError: invalid syntax

**Comment by Chuhao95** [comment]
Also have the same issue

**Comment by wsyzwddsg111** [comment]
first , you have to pip install poetry
then run  poetry install
you will see  your current project in .venv/site-packages as a module
but there are so many other package issues when running it in local, so , i just give up....
